### ISSUE TITLE
Домашняя работа 1

### ISSUE THREAD

**Issue by YumiYukiko** [ing-prog/webpy_2019_1_g2#1]
Козлова Катя
Линки: 1) https://github.com/YumiYukiko/Pythooon/blob/master/hm1.1.py
             2) https://github.com/YumiYukiko/Pythooon/blob/master/hm1.2.py

**Comment by vlasove** [comment]
`def NOD ():
    a = 0
    b = 0`

Для чего их занулять в языке с динамической типизацией?

**Comment by vlasove** [comment]
`r = 1`  где используется эта переменная в задаче с НОД?

**Comment by vlasove** [comment]
Сделай ввод за пределами функции NOD() 
Функция должна выполнять расчет НОД и возвращать результат . Только и всего.
Ввод данных и вывод обычно в функции не помещают в таком случае

**Comment by vlasove** [comment]
Что будет в задаче с квадратным уравнением, если я введу A =0, B= 0, C =1?

**Comment by vlasove** [comment]
Ввод за пределами функции. Она нужна только для подсчета корней и все. Не перегружай их
`def equation(a,b,c):`

**Comment by vlasove** [comment]
Сделай плиз вывод следующим образом :
Если есть 2 корня ---- то выводится просто 2 числа через пробел или запятую (не важно)
Если корень 1 -- выводится только это число
Если корней нет -- пустая строка

**Comment by YumiYukiko** [comment]
Принято, допиливаю. Исправленное скидывать заново, или просто сюда отметить, что файлы изменены?

**Comment by vlasove** [comment]
> Принято, допиливаю. Исправленное скидывать заново, или просто сюда отметить, что файлы изменены?

Просто отметь

**Comment by YumiYukiko** [comment]
> `def NOD (): a = 0 b = 0`
> 
> Для чего их занулять в языке с динамической типизацией?

У меня стоит цикл на ввод до тех пор, пока оба числа не станут больше нуля. Обнуление, чтобы цикл запустился

**Comment by YumiYukiko** [comment]
Поправила всё, что было упомянуто выше о7

**Comment by vlasove** [comment]
> Поправила всё, что было упомянуто выше о7

В задаче с NOD не нужен флаг %0.3f - ты выводишь int. НОД, насколько я понимаю, у натуральных чисел - всегда число натуральное. В целом - код ок.

**Comment by vlasove** [comment]
> > Поправила всё, что было упомянуто выше о7
> 
> В задаче с NOD не нужен флаг %0.3f - ты выводишь int, значит %i. НОД, насколько я понимаю, у натуральных чисел - всегда число натуральное. В целом - код ок.

В задаче с квадратным уравнением наоборот - убери точность на выводе, оставь %f. Пока твое решение прошло 2 теста из 30

**Comment by Cca-ine** [comment]
Смирнова
1)https://github.com/Cca-ine/python/blob/master/1/nod

**Comment by YumiYukiko** [comment]
Исправила задачу с уравнениями, файл залила в соседнюю ветку equation, чтобы оба варианта оставались живыми

**Comment by vlasove** [comment]
Что выведет нод при а= 0, b = 5?

**Comment by YumiYukiko** [comment]
> Что выведет нод при а= 0, b = 5?

Сейчас ничего, потому что ограничение не даст ввести. Если его убрать -- выведет 5 :^)

**Comment by YumiYukiko** [comment]
> > Что выведет нод при а= 0, b = 5?
> 
> Сейчас ничего, потому что ограничение не даст ввести. Если его убрать -- выведет 5 :^)

Поправила ограничение, выводит 5

**Comment by vlasove** [comment]
Для чего переменная i в функции sqrt?

**Comment by YumiYukiko** [comment]
Привычка :') Сколько теперь тестов проходит программа?

**Comment by vlasove** [comment]
> Привычка :') Сколько теперь тестов проходит программа?

Мертвого когда не должно быть. Старайся убирать его по возможности

**Comment by vlasove** [comment]
Ты умница. Зачет за дз
