### ISSUE TITLE
Hw1

### ISSUE THREAD

**Issue by Cca-ine** [ing-prog/webpy_2019_1_g2#2]
Смирнова 
1) https://github.com/Cca-ine/python/blob/master/1/nod
2) https://github.com/Cca-ine/python/blob/master/1/equation

**Comment by vlasove** [comment]
В задаче с NOD --- `return A  #nod`  этот коммент вообще к чему? Если он не несет никакой информации , то лучше его убрать.

**Comment by vlasove** [comment]
Что будет если я на вход твоей программе  NOD кину A = 0, B = 15?

**Comment by vlasove** [comment]
`while not A==B:` это лучше заменить на `A!=B` . В этом случае сравниваются 2 числовые переменные и так читаемость лучше.

**Comment by vlasove** [comment]
Задача квадратное уравнение.
Сделай пожалуйста вывод следующим образом :
Если есть 2 корня ---- то выводится просто 2 числа через пробел или запятую (не важно) (флаг форматирования только %f, без точности)
Если корень 1 -- выводится только это число
Если корней нет -- пустая строка

**Comment by vlasove** [comment]
Небольшая путаница с обозначениями `vr` и `D`. Логично было бы,  что  D - это и есть выражение дискриминанта, а не его корень

**Comment by vlasove** [comment]
В целом код по квадратному уравнению ок. Поправь мелочи те, что выше написал, я прогоню тесты

**Comment by Cca-ine** [comment]
Всё исправила.

**Comment by vlasove** [comment]
`else:`
           ` print("%f %f",x1,x2)`

Это работает?

**Comment by Cca-ine** [comment]
> 
> 
> `else:`
> ` print("%f %f",x1,x2)`
> 
> Это работает?

исправила... исправила

**Comment by vlasove** [comment]
Ок , вижу все. На будущее 2 замечания.
1) Все функции, определенные в программе в питоне должны определяться сразу после блоков import 
2) Немного аккуратнее с названием переменных, читать код сложно когда значения у переменной об одном, а называется она иначе

**Comment by vlasove** [comment]
Ты молодец. Зачет
