### ISSUE TITLE
Дз. Овсепян Т.

### ISSUE THREAD

**Issue by Tatevik04** [ing-prog/webpy_2019_1_g2#3]
https://github.com/Tatevik04/GetNod/blob/master/ДЗ

**Comment by Tatevik04** [comment]
https://github.com/Tatevik04/-/blob/master/Уравнение

**Comment by vlasove** [comment]
Что выдаст твой НОД если ввести ему 0 и 15?

**Comment by vlasove** [comment]
Во второй задаче у тебя сейчас ошибка с отступами - пофиксить нужно

**Comment by Tatevik04** [comment]
Поняла, в НОД сделаю проверку на ввод нуля, чтобы не делить на него.

**Comment by Tatevik04** [comment]
В задании на нахождение НОД сделана проверка на ввод 0. Вводя ноль, пользователь будет получать возможность ввести значения ещё раз.

**Comment by Tatevik04** [comment]
В уравнении ошибка с отступом в последнем “elif”?

**Comment by vlasove** [comment]
В задаче с нод нулевой ввод должен обрабатываться и выдавать корректный результат. Т.е. нод(0,25) = 25

**Comment by vlasove** [comment]
В задаче с уравнением - последний  if неверно написан

**Comment by Tatevik04** [comment]
> В задаче с нод нулевой ввод должен обрабатываться и выдавать корректный результат. Т.е. нод(0,25) = 25

Можете подсказать, пожалуйста, как это сделать? Если разрешить на вход ноль, то получается нужно менять условие для while, ведь цикл работает, пока значения не обнуляться.

**Comment by Tatevik04** [comment]
> В задаче с уравнением - последний if неверно написан

Я исправила) Можете посмотреть? Вроде, верно.

**Comment by vlasove** [comment]
В НОДе обработай случай нулевого ввода.
В уравнении - ввожу А=1, В = 0, С = 1 - получаю действительные корни. Это как?
Свожу задачу к линейной - ответ не выводится (А =0, В=1,С=1)

**Comment by vlasove** [comment]
В задаче с уравнением сделай плиз вывод следующим образом :
Если есть 2 корня ---- то выводится просто 2 числа через пробел или запятую (не важно)
Если корень 1 -- выводится только это число
Если корней нет -- пустая строка

**Comment by vlasove** [comment]
Умница. Зачет
