### ISSUE TITLE
Abakumov HW_1

### ISSUE THREAD

**Issue by Lesh4** [ing-prog/webpy_2019_1_g2#4]
1) https://github.com/Lesh4/HW_1/blob/master/NOD.py
2) https://github.com/Lesh4/HW_1/blob/master/quadratic_equation.py

**Comment by vlasove** [comment]
НОД (0, 15) вроде равен 15. Твоя прога так умеет?

**Comment by vlasove** [comment]
В задаче с квадратным уравнением вывод сделай таким :
Если есть 2 корня ---- то выводится просто 2 числа через пробел или запятую (не важно)
Если корень 1 -- выводится только это число
Если корней нет -- пустая строка

**Comment by Lesh4** [comment]
> НОД (0, 15) вроде равен 15. Твоя прога так умеет?
Научил

> В задаче с квадратным уравнением вывода сделай такая: 
> Если есть 2 ---- корня то выводится просто 2 число через пробел или запятая (не важно) 
> Если корень 1 - это только вывожусь Число 
> Если Корни пойти - пустая строка
Поправил

**Comment by Lesh4** [comment]
@vlasove пофиксил

**Comment by vlasove** [comment]
Для чего прога с НОДом просит 2 раза вводить эти числа?  Ввод одноразовый происходит

**Comment by vlasove** [comment]
Код с уравнением:
```    elif (a==0 or a!=0) and b!=0:
        if a!=0 and c==0: ```

**Comment by Lesh4** [comment]
> Для чего прога с НОДом просит 2 раза вводить эти числа? Ввод одноразовый происходит
> К тому же в условии написано по поводу отрицательных чисел (их на вход программе не подают)

Ага, понял, принял, ТЗ невнимательно прочитал. Поправил. Только вопрос: если на входе будут даны два 0, то какой НОД? И если это предотвращать, то получается нужно организовать цикл, на проверку ввода пользователя? (a=0, b=0 и цикл while a==0 and b==0: ввод)

**Comment by Lesh4** [comment]
> Код с уравнением:
> ` elif (a==0 or a!=0) and b!=0: if a!=0 and c==0: `
> Что делает этот блок?

Здесь 2 условия в одно засунул. Получается вот так, если не помещать все в одно

**Comment by vlasove** [comment]
> > Для чего прога с НОДом просит 2 раза вводить эти числа? Ввод одноразовый происходит
> > К тому же в условии написано по поводу отрицательных чисел (их на вход программе не подают)
> 
> Ага, понял, принял, ТЗ невнимательно прочитал. Поправил. Только вопрос: если на входе будут даны два 0, то какой НОД? И если это предотвращать, то получается нужно организовать цикл, на проверку ввода пользователя? (a=0, b=0 и цикл while a==0 and b==0: ввод)

НОД определен , вообще говоря, для любой пары целых чисел. В случае, когда НОД(0,0) -> 0

**Comment by vlasove** [comment]
> > Код с уравнением:
> > `elif (a==0 or a!=0) and b!=0: if a!=0 and c==0:`
> > Что делает этот блок?
> 
> Здесь 2 условия в одно засунул. Получается вот так, если не помещать все в одно
> 
> ```
> elif a==0 and b!=0 and c!=0:
>     x=-c/b
>     print(x)
> elif a!=0 and b!=0 and c==0:
>     x1=0
>     x2=-b/a
>     print("%f %f" %(x1,x2)) 
> ```
> Т.е. первое, это решение уравнения вида: 4х - 4 = 0
> второе: 4х^2 - 4х = 0

`(a==0 or a!=0)` я имел в виду, что такое условие выполняется абсолютно при любом вводе и его можно убрать

**Comment by vlasove** [comment]
Внимательно разбери случаи разного ввода нулевых значений коэффициентов в уравнении. Твоя программа на них падает

**Comment by Lesh4** [comment]
@vlasove, исправил уравнение
https://github.com/Lesh4/HW_1/blob/master/quadratic_equation.py

**Comment by vlasove** [comment]
Ок. Молодец) Зачет за дз ставлю. Подумай о том, как можно решить эту задачу в 3 раза короче
