### ISSUE TITLE
HW1_Kovakevsky

### ISSUE THREAD

**Issue by EvgKovalevsky** [ing-prog/webpy_2019_1_g2#5]
https://github.com/EvgKovalevsky/Python/blob/master/NOD.py
https://github.com/EvgKovalevsky/Python/blob/master/Equation.py

**Comment by vlasove** [comment]
Расчетные функции обычно возвращают значение, а не вывод в поток. Поэтому поправь ее, добавив честный return (a+b)

**Comment by vlasove** [comment]
Уравнение - ввожу A=0, B=0, C = 1 -- твоя прога падает

**Comment by EvgKovalevsky** [comment]
https://github.com/EvgKovalevsky/Python/blob/master/HW1/NOD.py
https://github.com/EvgKovalevsky/Python/blob/master/HW1/Equation.py

**Comment by vlasove** [comment]
В задаче с уравнением сделай плиз вывод следующим образом :
Если есть 2 корня ---- то выводится просто 2 числа через пробел или запятую (не важно)
Если корень 1 -- выводится только это число
Если корней нет -- пустая строка

**Comment by EvgKovalevsky** [comment]
https://github.com/EvgKovalevsky/Python/blob/master/HW1/Equation.py

**Comment by vlasove** [comment]
Красавчик. Зачет за дз
