### ISSUE TITLE
Pchelintseva Nastya

### ISSUE THREAD

**Issue by AnastasiaPomegranate** [ing-prog/webpy_2019_1_g2#6]
https://github.com/AnastasiaPomegranate/HomeworkPchel/blob/master/1lesson/1ex.py
https://github.com/AnastasiaPomegranate/HomeworkPchel/blob/master/1lesson/2ex.py

**Comment by vlasove** [comment]
`NOD=A+B` Для чего этот легаси код в функции НОД?

**Comment by vlasove** [comment]
Уравнение - случай ввода A=0, B=0, C=1 оставляет желать лучшего. Что должно выводиться в таком случае и как ведет сейчас себя твоя программа?

**Comment by AnastasiaPomegranate** [comment]
В первой программе забыла убрать эту строку

**Comment by AnastasiaPomegranate** [comment]
https://github.com/AnastasiaPomegranate/HomeworkPchel/blob/master/1lesson/1ex.py
https://github.com/AnastasiaPomegranate/HomeworkPchel/blob/master/1lesson/2ex.py

**Comment by vlasove** [comment]
Вроде бы код ок, чтобы я тесты прогнал в задаче с уравнением сделай плиз вывод следующим образом :
Если есть 2 корня ---- то выводится просто 2 числа через пробел или запятую (не важно)
Если корень 1 -- выводится только это число
Если корней нет -- пустая строка

**Comment by AnastasiaPomegranate** [comment]
https://github.com/AnastasiaPomegranate/HomeworkPchel/blob/master/1lesson/2ex.py

**Comment by vlasove** [comment]
Молодец) Зачет
