### ISSUE TITLE
Xenia Yashina 

### ISSUE THREAD

**Issue by iamxni** [ing-prog/webpy_2019_1_g2#7]
1 - https://github.com/iamxni/1/blob/master/1.py
2 - https://github.com/iamxni/2/blob/master/2.py

**Comment by vlasove** [comment]
Неплохо,  чтобы я тесты прогнал в задаче с уравнением сделай плиз вывод следующим образом :
Если есть 2 корня ---- то выводится просто 2 числа через пробел или запятую (не важно)
Если корень 1 -- выводится только это число
Если корней нет -- пустая строка

**Comment by iamxni** [comment]
Исправила.

**Comment by vlasove** [comment]
Умница! Код довольно неплох. Зачет за дз
