### ISSUE TITLE
ДЗ Борисова Ивана

### ISSUE THREAD

**Issue by Ivan3b** [ing-prog/webpy_2019_1_g2#9]
https://github.com/Ivan3b/-Python/blob/master/%D0%9D%D0%9E%D0%94
https://github.com/Ivan3b/-Python/blob/master/%D0%BA%D0%B2%D0%B0%D0%B4%D1%80%D0%B0%D1%82%D0%BD%D1%8B%D0%B9%20%D0%BA%D0%BE%D1%80%D0%B5%D0%BD%D1%8C

**Comment by Ivan3b** [comment]
блин, не то

**Comment by Ivan3b** [comment]
вот задание с квадратным уравнением
https://github.com/Ivan3b/-Python/blob/master/%D0%BA%D0%B2%D0%B0%D0%B4%D1%80%D0%B0%D1%82%D0%BD%D0%BE%D0%B5%20%D1%83%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5

**Comment by vlasove** [comment]
НОД код отличный!

**Comment by vlasove** [comment]
Уравнение падает при 0 0 1

**Comment by Ivan3b** [comment]
переделал

**Comment by vlasove** [comment]
> переделал

Не вижу, все равно падает на 0 0 1, выдавая неверный результат.
Избавься от непонятных сообщений.
сделай плиз вывод следующим образом :
Если есть 2 корня ---- то выводится просто 2 числа через пробел или запятую (не важно)
Если корень 1 -- выводится только это число
Если корней нет -- пустая строка

**Comment by vlasove** [comment]
Правки когда будут?
